FROM amazoncorretto:17.0.3-alpine3.15

# Install nginx
RUN apk update && apk add --no-cache nginx curl nginx-mod-http-brotli

# Ensure www-data user exists
RUN set -eux; \
    adduser -u 82 -D -S -G www-data www-data

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./properties.json /usr/share/nginx/html/properties.json

# Set folder permission for www-data
RUN rm -f /etc/nginx/conf.d/default.conf \
    && chown -R www-data:www-data /var/lib/nginx && \
    chown -R www-data:www-data /var/log/nginx


EXPOSE 8000
