FROM rust:1.57 as builder

WORKDIR /usr/src

COPY . .

RUN cargo build --release

FROM debian:buster-slim

WORKDIR /usr/local/bin/api

RUN ls -al .

COPY --from=builder /usr/src/target/release .

EXPOSE 3030

CMD ["./api"]