FROM rust:1.57 as builder

WORKDIR /usr/src

COPY . .

RUN cargo build --release

FROM debian:buster-slim

WORKDIR /usr/local/bin/api

COPY --from=builder /usr/src/target/release .
COPY --from=builder /usr/src/properties.json .

RUN ls -al .

EXPOSE 3030

CMD ["./api"]